# Flags

ifeq ($(optimize),true)
  CFLAGS += -Wall -O3 -DHAVE_INLINE -DGSL_RANGE_CHECK_OFF
  ifeq ($(specialize),true)
     CFLAGS += -march=$(arch) -mfpmath=sse
  endif
else
  CFLAGS += -g -Wall
endif

#
ifeq ($(usesse),true)
  CFLAGS += -mmmx -msse -msse2 -msse3
endif

